#!/bin/bash
set -euo pipefail

# bootstrap-approle.sh — one-shot machine identity enrollment + init-script generator.
#
# Flow:
#   1. Operator SSHs into the server
#   2. Operator runs: bao login -method=oidc role=operator
#   3. Operator runs: bash bootstrap-approle.sh
#   4. Script creates an AppRole named after this host (if absent)
#   5. Script stores role_id + secret_id in /etc/bao/ (reuses existing secret_id)
#   6. Script generates ~/.local/bin/bao-auth (executable, host-specific)
#   7. Script generates ~/.config/direnv/lib/bao.sh (auto sourced in .envrc dirs)
#   8. Script revokes the operator's token and wipes the token file
#
# After this, the server authenticates on its own via AppRole.
# No human token retained, no browser needed for future auth.

VAULT_ADDR="${VAULT_ADDR:-https://bao.hnatekmar.xyz}"
export VAULT_ADDR

BAO_CONF_DIR="/etc/bao"
BAO_AUTH_BIN="$HOME/.local/bin/bao-auth"
DIRENV_LIB_DIR="$HOME/.config/direnv/lib"
ROLE_NAME="${1:-$(hostname)}"

# --- Pre-flight ---

bao token lookup >/dev/null 2>&1 || {
    echo "ERROR: No valid Bao token. Run 'bao login -method=oidc role=operator' first." >&2
    exit 1
}

mkdir -p "$BAO_CONF_DIR" "$(dirname "$BAO_AUTH_BIN")" "$DIRENV_LIB_DIR"

# --- Create AppRole for this machine (idempotent: bao write upserts) ---

echo "==> Creating AppRole: $ROLE_NAME"

bao write "auth/approle/role/$ROLE_NAME" \
    token_policies="default" \
    token_ttl=1h \
    token_max_ttl=4h \
    secret_id_ttl=0 \
    secret_id_num_uses=0

# --- Store role_id (always refresh; cheap) ---

ROLE_ID=$(bao read -field=role_id "auth/approle/role/$ROLE_NAME/role-id")
echo "$ROLE_ID" > "$BAO_CONF_DIR/role-id"
chmod 0640 "$BAO_CONF_DIR/role-id"

# --- Store secret_id (reuse only if the stored secret still logs in) ---

if [ -f "$BAO_CONF_DIR/secret-id" ]; then
    STORED_ROLE=$(cat "$BAO_CONF_DIR/role-id" 2>/dev/null)
    STORED_SECRET=$(cat "$BAO_CONF_DIR/secret-id")
    if [ -n "$STORED_ROLE" ] && [ -n "$STORED_SECRET" ] && \
       bao write -field=token "auth/approle/login" role_id="$STORED_ROLE" secret_id="$STORED_SECRET" >/dev/null 2>&1; then
        echo "==> Existing secret-id still valid for $ROLE_NAME; reusing."
    else
        echo "==> Existing secret-id invalid; generating a new one for $ROLE_NAME..."
        SECRET_ID=$(bao write -f -field=secret_id "auth/approle/role/$ROLE_NAME/secret-id")
        echo "$SECRET_ID" > "$BAO_CONF_DIR/secret-id"
        chmod 0600 "$BAO_CONF_DIR/secret-id"
    fi
else
    echo "==> Generating new secret_id for $ROLE_NAME..."
    SECRET_ID=$(bao write -f -field=secret_id "auth/approle/role/$ROLE_NAME/secret-id")
    echo "$SECRET_ID" > "$BAO_CONF_DIR/secret-id"
    chmod 0600 "$BAO_CONF_DIR/secret-id"
fi

echo "==> Credentials written to $BAO_CONF_DIR/"

# --- Generate ~/.local/bin/bao-auth (host-specific init script) ---
#
# Usage:
#   source <(bao-auth)        # shells / .envrc — exports VAULT_TOKEN
#   bao-auth --token          # scripts — prints token only
#   bao-auth --env            # prints export lines (same as default)

cat > "$BAO_AUTH_BIN" <<AUTH_EOF
#!/bin/bash
# Generated by bootstrap-approle.sh — machine identity auth for $ROLE_NAME.
# Do not edit; re-run bootstrap-approle.sh to regenerate.
set -euo pipefail

VAULT_ADDR="$VAULT_ADDR"
export VAULT_ADDR

BAO_CONF_DIR="$BAO_CONF_DIR"

ROLE_ID=\$(cat "\$BAO_CONF_DIR/role-id" 2>/dev/null) || {
    echo "ERROR: \$BAO_CONF_DIR/role-id missing. Run bootstrap-approle.sh." >&2
    exit 1
}
[ -r "\$BAO_CONF_DIR/secret-id" ] || {
    echo "ERROR: \$BAO_CONF_DIR/secret-id missing. Run bootstrap-approle.sh." >&2
    exit 1
}

# @-syntax: bao reads the secret from the file, so it never appears in `ps`.
TOKEN=\$(bao write -field=token "auth/approle/login" \\
    role_id="\$ROLE_ID" secret_id="@\$BAO_CONF_DIR/secret-id") || {
    echo "ERROR: AppRole login failed." >&2
    exit 1
}

case "\${1:-source}" in
    --token) echo "\$TOKEN" ;;
    --env|source)
        echo "export VAULT_ADDR='\$VAULT_ADDR'"
        echo "export VAULT_TOKEN='\$TOKEN'"
        ;;
    *)
        echo "Usage: bao-auth [--token|--env]" >&2
        exit 1
        ;;
esac
AUTH_EOF
chmod 0755 "$BAO_AUTH_BIN"

echo "==> Generated $BAO_AUTH_BIN"

# --- Generate direnv lib (sourced automatically in dirs with a .envrc) ---

cat > "$DIRENV_LIB_DIR/bao.sh" <<DIRENV_EOF
# Auto-generated by bootstrap-approle.sh — AppRole auth for direnv.
# Sourced in any directory containing an allowed .envrc.
source <("$BAO_AUTH_BIN")
DIRENV_EOF
chmod 0644 "$DIRENV_LIB_DIR/bao.sh"

echo "==> Generated $DIRENV_LIB_DIR/bao.sh"

# --- Dispose of operator token ---

bao token revoke -self 2>/dev/null || true
rm -f ~/.bao-token
unset VAULT_TOKEN

echo "==> Operator token revoked. Server now uses AppRole '$ROLE_NAME'."
echo "==> In shells:        source <(bao-auth)"
echo "==> In scripts:       TOKEN=\$(bao-auth --token)"
echo "==> In direnv dirs:   (automatic — lib/bao.sh)"
